version: 2

.install_packages: &install_packages
  run:
    name: Install packages
    command: apk add sqlite-dev git build-base ruby-dev ruby-etc ruby-json

.restore_cache: &restore_cache
  restore_cache:
    keys:
      - cache-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - cache-v1-{{ .Branch }}
      - cache-v1

.save_cache: &save_cache
  save_cache:
    key: cache-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
    paths:
      - ./vendor/bundle

.install_dependencies: &install_dependencies
  run:
    name: Install dependencies
    command: bundle install --path vendor/bundle --binstubs

jobs:
  rspec:
    docker:
      - image: ruby:2.6-alpine
    steps:
      - checkout
      - *install_packages
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run:
          name: RSpec
          command: bundle exec rspec

  rufo:
    docker:
      - image: ruby:2.6-alpine
    steps:
      - checkout
      - *install_packages
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run:
          name: rufo
          command: bundle exec rufo src spec --check

workflows:
  version: 2
  test:
    jobs:
      - rspec
      - rufo
